### ISSUE TITLE
캐스팅 관련 수정사안

### ISSUE THREAD

**Issue by Su-Yong** [Ywoosang/C#1]
![image](https://user-images.githubusercontent.com/13764936/109344419-0ba7f300-78b2-11eb-8613-512cd7a3c404.png)
`(type)`방식으로 캐스팅을 해도 되긴하지만
`type()`방식으로 캐스팅 하는게 좀더 c스타일이여서 수정하는걸 추천드려요!

저도 잘 모르니 그냥 close해도 될거같아요... 지나가다가 의견 남겨봅니다

**Comment by Ywoosang** [comment]
@Su-Yong 

type() 방식이 `형변환할 타입(자료형을 가진 변수)` 처럼 사용하는 것을 말씀하시는건가요?
c 를 접한지 얼마 안 되어서 아는 지식은 적지만
형변환은 아래처럼 하면 오류가 나더라구요..

![image](https://user-images.githubusercontent.com/68385605/109399598-29935780-7987-11eb-8c69-5dcb765b2149.png)

별도의 방법이 있을까요 ? ㅠ.ㅠ

**Comment by Su-Yong** [comment]
헉 알고보니 cpp에서 부르는 c style 캐스팅이 저러한 방법이 사용되네요
그냥 c는 `(type)`으로 캐스팅한다고 합니다... 

close할께요 ㅠㅠ
